language: scala
jdk:
- openjdk8
script: sbt +compile
env:
  global:
    secure: C0bpzUBE2UXNJ30dyIQOc/6tpV7tUD5Sbyoob8MGdgn6pPYYE8A+CUxcc72++LhoI6Sz1m13X+fCw5E4vzxYaWkbSd8Hn2ODxL1fbWWnNUisCOXU503icjwQIZUHO/AEXO9wHdmMsXRCYkz9con/aBrglSudQGNBLoXj49lI0tCypM2FjuSIQHbZm1bRZ42syVVD1VtK4EcjzD1hpLMm2hxoetUPZNsN9J7AgBrG063eZJgwiY7soQf6LRi3XKVuIq/gM4SnkxQtYOthvCzbt8tDTQsP+L5yuv7tJAMStZq7XzU5UVfvAQGO/TkqJcg/S4RB8Z2MOGgrFFBRXaI6DViYkjoTsCKINWkTz4DNbrtRqftsXnjWdxIanzKRr8hTdcE77ecULBXqNDJhVssini7k+aEVGE12tc2EXbK8PYXk3cAmk6CJGFlZiwStemP6XyKEu/kdxd13Rxms4etPSX2x2cb8spzurwjJz1X0g4FKqa6UCWibnNNrESSxJY8hDit8nA/oJBCilOvWXsHrMw74dIc/hIYK4i8cLTMXldgWkKRjTLDDmsBIsqIiBdiU5I6HUmBJ3lJHKBEGn2/ys1LT20ik3rbaVX7h2Kx5aOzpBuj5zhdZe9fCcZAIRrBhfopmihQUflxeFTIsmPwhDMCTRm5OafRQWAD+NLimV8w=
before_deploy:
- openssl aes-256-cbc -K $encrypted_42ce39b74e5e_key -iv $encrypted_42ce39b74e5e_iv
  -in .travis/keys.tar.enc -out .travis/keys.tar -d
- tar xvf .travis/keys.tar
deploy:
  provider: script
  script: sbt +publishSigned "sonatypeReleaseAll com.criteo"
  skip_cleanup: true
  on:
    tags: true
    branch: master
