jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v2.3.4"
      - name: cache SBT
        uses: coursier/cache-action@v5
      - name: java 11 setup
        uses: "actions/setup-java@v1.4.3"
        with:
          architecture: x64
          java-package: jdk
          java-version: "11"
      - run: 'sbt "++${{ matrix.scala}} compile"'
    strategy:
      matrix:
        scala:
          - "2.12.11"
          - "2.12.12"
          - "2.12.13"
          - "2.13.2"
          - "2.13.3"
          - "2.13.4"
  publish:
    if: "github.event_name == 'push'"
    name: publish
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v2.3.4"
      - name: cache SBT
        uses: coursier/cache-action@v5
      - name: java 11 setup
        uses: "actions/setup-java@v1.4.3"
        with:
          architecture: x64
          java-package: jdk
          java-version: "11"
      - uses: "olafurpg/setup-gpg@v2"
      - env:
          PGP_PASSPHRASE: "${{ secrets.PGP_PASSPHRASE }}"
          PGP_SECRET: "${{ secrets.PGP_SECRET }}"
          SONATYPE_PASSWORD: "${{ secrets.SONATYPE_PASSWORD }}"
          SONATYPE_USERNAME: "${{ secrets.SONATYPE_USERNAME }}"
        name: "Publish ${{ github.ref }}"
        run: sbt ci-release
name: ci
on:
  pull_request: {}
  push: {}
